baseURL = "https://baswieringa.nl"
languageCode = "en-us"
disableKinds = ["taxonomy"]

[build]
    writeStats = true
    [[build.cachebusters]]
        source = 'layouts/.*'
        target = 'css'

[params]
    title = "Bas Wieringa"
    author = "Bas Wieringa"
    description = "Portfolio van Bas Wieringa"
    copyright = "© Bas Wieringa"

    # Profile section
    [params.profile]
        name = "Bas Wieringa"
        title = "Software Ontwikkelaar"
        photo = "images/profile.webp"
        photo_jpg = "images/profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-linkedin-in"
        url = "https://www.linkedin.com/in/bas-wieringa"
        text = "linkedin.com/in/bas-wieringa"
        title = "LinkedIn"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/broodroosterdev"
        text = "github.com/broodroosterdev"
        title = "GitHub"
		
	    [[params.social.list]]
        icon = "fas fa-envelope"
        url = "mailto:basmakes+resume@gmail.com"
        text = "basmakes@gmail.com"
        title = "Mail"	

    # Education section
    [params.education]
        title = "Opleiding"

        [[params.education.list]]
        degree = "HBO-ICT"
        college = "Windesheim Zwolle"
        dates = "sep. 2019 - jun. 2023"
        url = "https://www.windesheim.nl/over-windesheim/locatie-zwolle"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Fluent"
				
        [[params.language.list]]
        language = "Bird"
        level = "Basic"

    [params.aboutme]
        description = "Tagline. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

    # Experiences section
    [params.experiences]
        title = "Ervaring"

        [[params.jobs.list]]
        position = "Junior software ontwikkelaar"
        dates = "sep. 2023 - *Heden*"
        company = "Water Platform Company"
        link = "https://www.hydronet.com/"
        details = """
Ontwikkeling en onderhoud aan de frontend (Angular) en backend (ASP.NET) van HydroNET.
Ondersteuning bij infra werkzaamheden en opzetten van Kubernetes omgeving.
"""
	[[params.jobs.list]]
        position = "Afstudeerstage software ontwikkelaar"
        dates = "feb. 2023 - jun. 2023"
        company = "Water Platform Company"
        link = "https://www.hydronet.com/"
        details = """
Ontwikkelen van een verbeterde versie van de Scheduler binnen het HydroNET platform.
Verbeteringen doorgevoerd in de interne management tool van HydroNET, waaronder statistieken over uitgevoerde achtergrondtaken.
Gebruik gemaakt van Angular in de frontend en .NET C# in de backend en scheduler.
"""

        [[params.jobs.list]]
        position = "Vakkenvuller"
        dates = "mei 2018 - jan. 2023"
        company = "PLUS Wilmink"
        link = "https://www.plus.nl"
        details = "Geholpen als onderdeel van de vulploeg, laden/lossen en magazijn onderhouden."
        
    # Internships section
    [params.internships]
        title = "Stages"

        [[params.internships.list]]
        title = "Future Technology"
        dates = "sep. 2022 - jan. 2023"
        company = "Pharox"
        link = "https://pharox.io"
        description = """
Ontwikkelen van een proof-of-concept blockchain applicatie waarmee
het transport en onderhoud van industriële gasflessen wordt bijgehouden.
"""
		
		[[params.internships.list]]
        title = "Mobile Solutions"
        dates = "feb. 2022 - jun. 2022"
        company = "Behive"
        link = "https://www.behive.nl"
        description = """
Ontwikkelen van PWA (Progressive Web App) waarin gebruikers challenges over de natuur kunnen doen.
Gebruik gemaakt van React in de frontend en Java Spring Boot in de backend.
Hosting opgezet met Docker Compose inclusief een Github Actions ontwikkelstraat.
"""
        [[params.internships.list]]
        title = "Quality in Software Design"
        dates = "aug. 2021 - dec. 2021"
        company = "Djurve"
        link = "https://www.djurve.nl"
        description = """
Opzetten van een stabiele infrastructuur in Azure op basis van Nomad en Docker.
Dit in combinatie met het omvormen van de bestaande monolitische ASP.NET applicatie naar microservices.
"""

        [[params.internships.list]]
        title = "Web Development"
        dates = "apr. 2021 - jun. 2021"
        company = "California Harderwijk"
        link = "https://www.californiaharderwijk.nl"
        description = """
Ontwikkelen van een PWA (Progressive Web App) voor het aangeven van aanwezigheid en reserveren van werkruimtes.
Gebruik gemaakt van Vue en Tailwind in de frontend en een Directus CMS als backend.
"""
